// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkSs-gAj8i2-ev9XyLTJ7drT1cyAgnrg',
    appId: '1:957429577196:web:e1af1747f3f67e2c9f3cc9',
    messagingSenderId: '957429577196',
    projectId: 'flutter-cli-fire-1795a',
    authDomain: 'flutter-cli-fire-1795a.firebaseapp.com',
    storageBucket: 'flutter-cli-fire-1795a.firebasestorage.app',
    measurementId: 'G-3YH6D2BVDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzm6XVqEqPdGmBWDMhek_tRxpLBss5_E',
    appId: '1:957429577196:android:6a0683a6b797c7039f3cc9',
    messagingSenderId: '957429577196',
    projectId: 'flutter-cli-fire-1795a',
    storageBucket: 'flutter-cli-fire-1795a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLR9rYnk2G5v4xgONNaB2_gaqNSV7rJdA',
    appId: '1:957429577196:ios:484f50ba034581cd9f3cc9',
    messagingSenderId: '957429577196',
    projectId: 'flutter-cli-fire-1795a',
    storageBucket: 'flutter-cli-fire-1795a.firebasestorage.app',
    iosBundleId: 'com.tht.flutterclifirebase.flutterCliFirebase',
  );
}
